### ISSUE TITLE
Documented Example for Building Out SSM Doc with Association for Custom Inventory

### ISSUE THREAD

**Issue by sheldonhull** [scrthq/VaporShell#50]
This might not be in the scope, but as new user, your personal assistance has been invaluable for seeing how to use this. I've found the learning curve a bit steep, but with some practical examples maybe this can help other newer users. Here's my example, and any improved documentation would be amazing, or close if not a good fit for your time. This is what I mocked up, considering ways to decouple software and monitoring agent installation from being directly embedded into userdata. I think using SSM is a perfect fit for this, but have some stuff to wrap my head around. 

You might have some good advice with Vaporshell on adding association, and ensuring this stack doesn't impact other resources as it's a "utility" type of stack. 

```
Feature: Create Collection of SSM Docs From Script Files
```

```
Scenario: Install Chocolately Automatically on Instances with Specific Tag
Given SSM agent is installed on the machines with appropriate permissions
When I publish the stack of SSM docs
Then the docs are successfully created
And the name of the docs is clean and does not include hashes to allow calling in cfn-init for other stacks
And I can then create a successfully association for specific docs to EC2 instances with specific tag
And the association schedule can be set
And the association logs to an S3 bucket that is created if not already existing
```

```
Scenario: Choco is installed via SSM upon creation of EC2 instances with tag set
Given the SSM docs exist already
When EC2 instance is created
And the required tag is on it
Then I can enforce compliance by calling SSM doc from my template OR better yet have it triggered automatically in SSM with zero change to the other stacks
And choco is correctly installed
And inventory allows me to confirm compliance
```

```
## The second goal of this to ensure compliance and review items not complying in AWS System Manager Insights. Not sure if compliance can be set in cloudformation yet
Scenario: Inventory compliance is enforced by the collected inventory
Given the inventory has been successfully created
When I want to ensure that a specific version of a package is installed
Then I can view this compliance for package installation in AWS Systems manager
```

**Comment by scrthq** [comment]
Thanks for migrating the discussion over here, @sheldonhull! I'm always looking for ways to improve the documentation and included features within VaporShell, so feedback and insight is very welcome!

If you're creating the Association as well (vs associating instances during bootstrapping), you'll need the at least the following resources in your CloudFormation stack per document:
* [SSM Document](https://vaporshell.io/docs/glossary/New-VSSSMDocument)
* [SSM Association](https://vaporshell.io/docs/glossary/New-VSSSMAssociation)

The Association would need to have `Targets` specified (instead of `InstanceId`). The value for the `Targets` parameter would need to be created with [Add-VSSSMAssociationTarget](https://vaporshell.io/docs/glossary/Add-VSSSMAssociationTarget).

For the below stack, you would want to add the following tag to any resources you'd like to associate with that document:

```powershell
Add-VSTag -Key 'InstallChoco' -Value 'Yes'
```

Subsequently, any additional Docs/Associations you'd create would need to have those tags added as well for instances associating with multiple SSM Documents.

***

Here's a sample stack containing one SSM Document and it's Association followed by the resulting JSON and YAML:

```powershell
$commands = @(
    # Get-Content has a ton of hidden metadata, need to pipe to Out-String to get only the expected contents
    (Get-Content 'C:\Test\Get-ChocoPackages.ps1' | Out-String)
    'Get-ChocoPackages'
)

$ssmDocContent = [PSCustomObject]@{
    schemaVersion = "2.2"
    description   = "install chocolatey"
    mainSteps     = @(
        [pscustomobject]@{
            action       = "aws:runPowerShellScript"
            name         = 'chocoInstall' # no dashes
            precondition = @{StringEquals = @('platformType', "Windows")}
            inputs       = @{runCommand = $commands}
        }
    )
}

$template = Initialize-Vaporshell -Description "Core SSM Documents for shared use"
$chocoSSMDoc = New-VSSSMDocument -LogicalId 'ChocoInstallSSMDocument' -Content $ssmDocContent -DocumentType Command
$chocoSSMAssociate = New-VSSSMAssociation -LogicalId 'ChocoInstallSSMAssociation' -Name (Add-FnRef $chocoSSMDoc) -Targets @(
    (Add-VSSSMAssociationTarget -Key "tag:InstallChoco" -Values @('Yes','True'))
)
$template.AddResource($chocoSSMDoc,$chocoSSMAssociate)

$template.ToJSON()
$template.ToYAML()
```

```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "Core SSM Documents for shared use",
  "Resources": {
    "ChocoInstallSSMDocument": {
      "Type": "AWS::SSM::Document",
      "Properties": {
        "Content": {
          "schemaVersion": "2.2",
          "description": "install chocolatey",
          "mainSteps": [
            {
              "action": "aws:runPowerShellScript",
              "name": "chocoInstall",
              "precondition": {
                "StringEquals": [
                  "platformType",
                  "Windows"
                ]
              },
              "inputs": {
                "runCommand": [
                "\u003c#\r\n.Description\r\n    Inventory Packages for Choco on machine\r\n#\u003e\r\n\r\nfunction Get-ChocoPackages {\r\n    [cmdletbinding()]\r\n    param()\r\n\r\n\r\n    $results = choco list --local-only --limit-output\r\n    $data = $results | ForEach-Object {\r\n        $val = $_ -split \u0027\\|\u0027\r\n        [pscustomobject]@{package = $val[0]; version = $val[1]}\r\n    }\r\n    $CustomInventorySchema = [PSCustomObject]@{\r\n        SchemaVersion = \"1.0\"\r\n        TypeName      = \"Custom:ChocoInventory\"\r\n        Content       = $Data\r\n    }\r\n\r\n    $content = $CustomInventorySchema |  ConvertTo-Json -Depth 10\r\n    try\r\n    {\r\n        $instanceId = Invoke-RestMethod -uri http://169.254.169.254/latest/meta-data/instance-id -TimeoutSec 2 -ErrorAction SilentlyContinue\r\n    }\r\n    catch\r\n    {\r\n        Write-Warning \"Invoke-RestMethod to get metadata timed out. Ignore if this is being run on non-AWS instance\"\r\n    }\r\n    if (-not $InstanceId)\r\n    {\r\n        Write-Warning \"Failed to identify this as an AWS instance, saving to C:\\temp instead\"\r\n        $OutDir = (New-Item -Path \u0027C:\\temp\u0027 -ItemType Directory -Force).FullName\r\n    }\r\n    else\r\n    {\r\n\r\n        $OutDir = \"C:\\ProgramData\\Amazon\\SSM\\InstanceData\\\" + $instanceId + \"\\inventory\\custom\\\"\r\n    }\r\n    $filepath = Join-Path $OutDir \"ChocoInventory.json\"\r\n    if (-NOT (Test-Path $filepath))\r\n    {\r\n        New-Item $filepath -ItemType file\r\n    }\r\n    Set-Content -Path $filepath -Value $content\r\n    Write-Host \"Saved $(@($Data).Count) choco package content to: $FilePath\"\r\n}\r\n",
                  "Get-ChocoPackages"
                ]
              }
            }
          ]
        },
        "DocumentType": "Command"
      }
    },
    "ChocoInstallSSMAssociation": {
      "Type": "AWS::SSM::Association",
      "Properties": {
        "Name": {
          "Ref": "ChocoInstallSSMDocument"
        },
        "Targets": [
          {
            "Key": "tag:InstallChoco",
            "Values": [
              "Yes",
              "True"
            ]
          }
        ]
      }
    }
  }
}
```

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Core SSM Documents for shared use
Resources:
  ChocoInstallSSMDocument:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: '2.2'
        description: install chocolatey
        mainSteps:
          - action: aws:runPowerShellScript
            name: chocoInstall
            precondition:
              StringEquals:
                - platformType
                - Windows
            inputs:
              runCommand:
                - "<#\r\n.Description\r\n    Inventory Packages for Choco on machine\r\
                  \n#>\r\n\r\nfunction Get-ChocoPackages {\r\n    [cmdletbinding()]\r\
                  \n    param()\r\n\r\n\r\n    $results = choco list --local-only\
                  \ --limit-output\r\n    $data = $results | ForEach-Object {\r\n\
                  \        $val = $_ -split '\\|'\r\n        [pscustomobject]@{package\
                  \ = $val[0]; version = $val[1]}\r\n    }\r\n    $CustomInventorySchema\
                  \ = [PSCustomObject]@{\r\n        SchemaVersion = \"1.0\"\r\n  \
                  \      TypeName      = \"Custom:ChocoInventory\"\r\n        Content\
                  \       = $Data\r\n    }\r\n\r\n    $content = $CustomInventorySchema\
                  \ |  ConvertTo-Json -Depth 10\r\n    try\r\n    {\r\n        $instanceId\
                  \ = Invoke-RestMethod -uri http://169.254.169.254/latest/meta-data/instance-id\
                  \ -TimeoutSec 2 -ErrorAction SilentlyContinue\r\n    }\r\n    catch\r\
                  \n    {\r\n        Write-Warning \"Invoke-RestMethod to get metadata\
                  \ timed out. Ignore if this is being run on non-AWS instance\"\r\
                  \n    }\r\n    if (-not $InstanceId)\r\n    {\r\n        Write-Warning\
                  \ \"Failed to identify this as an AWS instance, saving to C:\\temp\
                  \ instead\"\r\n        $OutDir = (New-Item -Path 'C:\\temp' -ItemType\
                  \ Directory -Force).FullName\r\n    }\r\n    else\r\n    {\r\n\r\
                  \n        $OutDir = \"C:\\ProgramData\\Amazon\\SSM\\InstanceData\\\
                  \" + $instanceId + \"\\inventory\\custom\\\"\r\n    }\r\n    $filepath\
                  \ = Join-Path $OutDir \"ChocoInventory.json\"\r\n    if (-NOT (Test-Path\
                  \ $filepath))\r\n    {\r\n        New-Item $filepath -ItemType file\r\
                  \n    }\r\n    Set-Content -Path $filepath -Value $content\r\n \
                  \   Write-Host \"Saved $(@($Data).Count) choco package content to:\
                  \ $FilePath\"\r\n}\r\n"
                - Get-ChocoPackages
      DocumentType: Command
  ChocoInstallSSMAssociation:
    Type: AWS::SSM::Association
    Properties:
      Name: !Ref 'ChocoInstallSSMDocument'
      Targets:
        - Key: tag:InstallChoco
          Values:
            - 'Yes'
            - 'True'
```
