### ISSUE TITLE
MetaData LogicalID is not allowing use of Colons

### ISSUE THREAD

**Issue by cbrowningcp** [scrthq/VaporShell#53]
Currently, you are forced to only Alphanumeric characters when specifying a LogicalID for new-vapormetadata (and, I assume, everywhere else). This prevents a couple of usages requiring colons - namely, using cloudinit, which requires something like
```
MetaData:
    AWS::CloudFormation::Init:
                configSets:
                    WindowsConfig:
                        - "SetTimezone"
                        - "ConfigureAWSTools"
                        - "InstallDeploymentBundle"
                        - "SetEnvironmentVariables"
                SetTimezone:
                    commands:
                        01-set_timezone:
                            command: "tzutil /s \"Eastern Standard Time\""
                            waitAfterCompletion: 0
```

and so on. 

If there is another method to utilize this I am missing, I apologize.
