### ISSUE TITLE
MetaData formatting diferences when used in LaunchConfiguratoins

### ISSUE THREAD

**Issue by cbrowningcp** [scrthq/VaporShell#55]
It seems there are some formatting differences when you add metadata to the whole template, versus just in a launch configuration. As an example, see [this gist](https://gist.github.com/cbrowningcp/4aa57f8fa4bc55f66167ca0516a4f0ad).

Ideally, the metadata under the launch configuration would have the same formatting as what is under the generic metadata area at the top of the template, specifically ,without the "LogicalId:" in front of the provided ID or "Props:" header.

**Comment by scrthq** [comment]
Hey @cbrowningcp - I should probably clarify that the `New-Vapor*` functions are typically reserved for those top-level nodes in the template. I should also expand on the input type validation against the `Metadata` property on Resource Types to provide better contextual awareness on this (and/or add handling in the event that `New-VaporMetadata` is used so it resolves as expected.

Currently, the `Metadata` property on individual resource types expects a PSCustomObject. The input to that object is translated literally to the resulting template, so using `New-VaporMetadata` will resolve to the actual object that `New-VaporMetadata` produces vs the massaged object that is visible when you use it on the top-level `Metadata` node.

Here's the actual parameter and it's `ValidateScript` attribute for visibility:

```powershell
[parameter(Mandatory = $false)]
[ValidateScript( {
        $allowedTypes = "System.Management.Automation.PSCustomObject"
        if ([string]$($_.PSTypeNames) -match "($(($allowedTypes|ForEach-Object{[RegEx]::Escape($_)}) -join '|'))") {
            $true
        }
        else {
            $PSCmdlet.ThrowTerminatingError((New-VSError -String "The UpdatePolicy parameter only accepts the following types: $($allowedTypes -join ", "). The current types of the value are: $($_.PSTypeNames -join ", ")."))
        }
    })]
$Metadata
```

Here's how I would approach your example of adding the same cfn-init metadata directly to the resource itself (casting to PSCustomObject is currently needed, will work on enabling more types there like Hashtables or OrderedDictionary's as well):

```powershell
$t = Initialize-Vaporshell "testing resource metadata"
$asLC = New-VSAutoScalingLaunchConfiguration "LaunchConfigurationApplicationOnDemand" -ImageId 'ami-1234567' -InstanceType 't2.micro' -Metadata ([PSCustomObject]@{
    'AWS::CloudFormation::Init' = @{
        configSets  = @{
            WindowsConfig = @(
                'SetTimezone'
                'ConfigureAWSTools'
                'InstallDeploymentBundle'
                'SetEnvironmentVariables'
                'SetEnvironmentVariables'
            )
        }
        SetTimezone = @{
            commmands = [ordered]@{
                '01-set_timezone' = [ordered]@{
                    command                  = 'tzutil /s "Eastern Standard Time"'
                    waitUntilAfterCompletion = 0
                }
            }
        }
    }
})
$t.AddResource($asLc)
$t.ToYaml()
```

Resulting YAML:

```yaml
Description: testing resource metadata
Resources:
  LaunchConfigurationApplicationOnDemand:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-1234567
      InstanceType: t2.micro
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          WindowsConfig:
            - SetTimezone
            - ConfigureAWSTools
            - InstallDeploymentBundle
            - SetEnvironmentVariables
            - SetEnvironmentVariables
        SetTimezone:
          commmands:
            '01-set_timezone':
              command: tzutil /s "Eastern Standard Time"
              waitUntilAfterCompletion: 0
```

***

Hopefully that makes sense! I appreciate you raising these concerns and will get some clarification implemented in the code to assist with that, for sure 😃
